/* eslint-disable */
// Placeholder for the 0001_init migration.
//
// In Medusa 2, real migrations are GENERATED by `medusa db:generate <name>` and live at:
//   node_modules/.cache/medusa/migrations/
//
// They are then APPLIED by `medusa db:migrate`. After first run, copy the generated
// file(s) into this folder and commit them so future deploys are reproducible.
//
// To bootstrap this scaffold's first migration against a real Postgres:
//   1. cp apps/backend/.env.example apps/backend/.env
//   2. fill DATABASE_URL
//   3. medusa db:create
//   4. medusa db:generate init_schema --interactive=false
//   5. cp node_modules/.cache/medusa/migrations/*.sql apps/backend/medusa-db/migrations/0001_init/
//   6. medusa db:migrate
//
// On Windows this path is env-blocked (no Postgres). Tests use pg-mem.

SELECT 'init schema placeholder — run medusa db:generate to materialize real migrations' AS note;
